---
- name: Configure network range for pod 
  command: sudo kubeadm init --pod-network-cidr 192.168.0.0/16 --kubernetes-version 1.23.0
  when: node_role == "master"
- name: configuring of cluster network 
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  when: node_role  == "master"
- name: generate command to join cluster 
  shell: kubeadm token create --print-join-command > /joincluster.txt
  when: node_role  == "master"
- name: Ensure that .kube directory exists
  file:
    path: /home/automation/.kube
    recurse: yes
    state: directory
  when: node_role  == "master"
- name: Copy configuration for regular user
  copy:
    dest: /home/automation/.kube/config
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    owner: automation
    group: automation
  when: node_role  == "master"
- name: copy file to join cluster
  fetch:
    src: /joincluster.txt
    dest: /home/automation/
    flat: yes
  when: node_role  == "master"
- name: copy join command on worker node
  copy: 
    src: /home/automation/joincluster.txt
    dest: /joincluster.sh
    owner: automation
    group: automation
    mode: '0755'
  when: node_role  == "worker"
- name: join cluster
  shell: /./joincluster.sh 
  when: node_role  == "worker"
- name: delete file to join cluster
  file: 
    path: /joincluster.sh
    state: absent
  when: node_role  == "worker"
