---
- name: Ensure apt list dir exists
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755
- name: update of repos
  apt:
    update_cache: yes
- name: install containerd apt-transport-https curl
  apt: 
    name: "{{ item.name }}" 
    state: present
    force_apt_get: yes
  loop: "{{ simple_packages }}"
- name: Ensure directory /etc/containerd exist
  file: 
    path: /etc/containerd
    recurse: yes
    state: directory
- name: Generate default configuration
  shell: sudo containerd config default | sudo tee /etc/containerd/config.toml
  notify: Restart containerd 
 
